// ../types.ts
export interface StockItem {
  id: number; // Changed to number to match salesreportid
  name: string;
  quantity: number;
  unit: string;
  specifications?: string;
  category: string;
  pricePerUnit: number;
  supplierId?: string | null;
  addedBy: string;
  dateAdded: string;
  lastUpdated: string;
  threshold: number;
  barcode?: string;
  imageUrl?: string;
  productId?: number; // Added to link with products table
}

export interface Transaction {
  id?: number; // Optional if generated by Supabase
  timestamp?: string; // Optional if omitted
  productid: number;
  productname: string;
  type: string;
  quantity: number;
  userId: string;
  userName: string;
  reason: string;
  transferredTo: string;
  department: string;
  notes: string;
  status: string;
  createdat?: string; // Optional if handled by Supabase
}

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
  rating: number;
  onTimeDelivery: number;
}

export interface Department {
  id: string;
  name: string;
  head: string;
  location: string;
}

// Added for Sales Summary
export interface SalesSummary {
  totalCylinders: number;
  totalSalesValue: number;
  lowStockCylinders: number;
  recentSales: number;
  productSummary: { name: string; value: number }[];
}

// Added for Low Stock Items
export interface LowStockItem {
  id: number;
  name: string;
  quantity: number;
  threshold: number;
}