// ../types.ts
export interface StockItem {
  id: number; // Matches salesreportid from Supabase
  name: string;
  quantity: number;
  unit: string;
  specifications?: string;
  category: string;
  pricePerUnit: number;
  supplierId?: string | null;
  addedBy: string;
  dateAdded: string;
  lastUpdated: string;
  threshold: number;
  barcode?: string | null;
  imageUrl?: string | null;
  productId?: number; // Links with products table
}

export interface Transaction {
  id?: number; // Optional if generated by Supabase
  timestamp?: string; // Optional if omitted
  productid: number;
  productname: string;
  type: string;
  quantity: number;
  userId: string;
  userName: string;
  reason: string;
  transferredTo: string;
  department: string; // Kept as optional default 'N/A'
  notes: string;
  status: string;
  createdat?: string; // Optional if handled by Supabase
}

export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  email: string;
  phone: string;
  address: string;
  rating: number;
  onTimeDelivery: number;
}

// Removed Department interface since not needed

// Updated for Sales Summary to match StockContext usage
export interface SalesSummary {
  totalItems: number; // Total number of items (cylinders in this case)
  totalValue: number; // Total sales value
  lowStockItems: number; // Number of items below threshold
  recentTransactions: number; // Sales in the last 7 days
  categorySummary: Record<string, number>; // Summary by category (currently empty)
  totalCylinders: number; // Total cylinders
  lowStockCylinders: number; // Number of low stock cylinders
  productSummary: { name: string; value: number }[]; // Summary by product
<<<<<<< HEAD
}

=======
}
export interface User {
  id: string;
  username: string;
  email: string;
  role: 'admin' | 'staff' | 'viewer';
  firstName: string;
  lastName: string;
  createdAt: string;
  mfaEnabled: boolean;
  lastLogin?: string;
  photo?: string; // Added for Profile.tsx compatibility
}

export interface Notification {
  id: number;
  type: 'transaction' | 'stock' | 'customer' | 'distributed';
  message: string;
  timestamp: string;
  viewed: boolean;
}
>>>>>>> 6b6b1c6 (More updates after rebase)
// Updated for Low Stock Items
export interface LowStockItem {
  id: number;
  name: string;
  quantity: number;
  threshold: number;
}